### ISSUE TITLE
run บน server production

### ISSUE THREAD

**Issue by menphurk** [somprasongd/thai-smartcard-nodejs#8]
ผมได้ลอง run prod pm2 ตาม readme แล้ว ตัว server local เอง หมุนตลอดเลยครับ มีวิธีแก้ไขยังไงครับ

**Comment by somprasongd** [comment]
> ผมได้ลอง run prod pm2 ตาม readme แล้ว ตัว server local เอง หมุนตลอดเลยครับ มีวิธีแก้ไขยังไงครับ

มีรูป log ของ pm2 ให้ดูมั้ยครับ

**Comment by menphurk** [comment]
> > ผมได้ลอง run prod pm2 ตาม readme แล้ว ตัว server local เอง หมุนตลอดเลยครับ มีวิธีแก้ไขยังไงครับ
> 
> มีรูป log ของ pm2 ให้ดูมั้ยครับ


`Error: \\?\C:\inetpub\wwwroot\thaismartcardtrc\node_modules\@pokusew\pcsclite\build\Release\pcsclite.node is not a valid Win32 application.
\\?\C:\inetpub\wwwroot\thaismartcardtrc\node_modules\@pokusew\pcsclite\build\Release\pcsclite.node
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1122:18)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at Module.Hook._require.Module.require (C:\Users\Administrator\AppData\Roaming\npm\node_modules\pm2\node_modules\require-in-the-middle\index.js:80:39)
    at require (internal/modules/cjs/helpers.js:88:18)
    at bindings (C:\inetpub\wwwroot\thaismartcardtrc\node_modules\bindings\bindings.js:112:48)
    at Object.<anonymous> (C:\inetpub\wwwroot\thaismartcardtrc\node_modules\@pokusew\pcsclite\lib\pcsclite.js:4:37)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
Error: \\?\C:\inetpub\wwwroot\thaismartcardtrc\node_modules\@pokusew\pcsclite\build\Release\pcsclite.node is not a valid Win32 application.
\\?\C:\inetpub\wwwroot\thaismartcardtrc\node_modules\@pokusew\pcsclite\build\Release\pcsclite.node
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1122:18)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at Module.Hook._require.Module.require (C:\Users\Administrator\AppData\Roaming\npm\node_modules\pm2\node_modules\require-in-the-middle\index.js:80:39)
    at require (internal/modules/cjs/helpers.js:88:18)
    at bindings (C:\inetpub\wwwroot\thaismartcardtrc\node_modules\bindings\bindings.js:112:48)
    at Object.<anonymous> (C:\inetpub\wwwroot\thaismartcardtrc\node_modules\@pokusew\pcsclite\lib\pcsclite.js:4:37)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
Error: \\?\C:\inetpub\wwwroot\thaismartcardtrc\node_modules\@pokusew\pcsclite\build\Release\pcsclite.node is not a valid Win32 application.
\\?\C:\inetpub\wwwroot\thaismartcardtrc\node_modules\@pokusew\pcsclite\build\Release\pcsclite.node
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1122:18)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at Module.Hook._require.Module.require (C:\Users\Administrator\AppData\Roaming\npm\node_modules\pm2\node_modules\require-in-the-middle\index.js:80:39)
    at require (internal/modules/cjs/helpers.js:88:18)
    at bindings (C:\inetpub\wwwroot\thaismartcardtrc\node_modules\bindings\bindings.js:112:48)
    at Object.<anonymous> (C:\inetpub\wwwroot\thaismartcardtrc\node_modules\@pokusew\pcsclite\lib\pcsclite.js:4:37)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
Error: \\?\C:\inetpub\wwwroot\thaismartcardtrc\node_modules\@pokusew\pcsclite\build\Release\pcsclite.node is not a valid Win32 application.
\\?\C:\inetpub\wwwroot\thaismartcardtrc\node_modules\@pokusew\pcsclite\build\Release\pcsclite.node
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1122:18)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at Module.Hook._require.Module.require (C:\Users\Administrator\AppData\Roaming\npm\node_modules\pm2\node_modules\require-in-the-middle\index.js:80:39)
    at require (internal/modules/cjs/helpers.js:88:18)
    at bindings (C:\inetpub\wwwroot\thaismartcardtrc\node_modules\bindings\bindings.js:112:48)
    at Object.<anonymous> (C:\inetpub\wwwroot\thaismartcardtrc\node_modules\@pokusew\pcsclite\lib\pcsclite.js:4:37)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
Error: \\?\C:\inetpub\wwwroot\thaismartcardtrc\node_modules\@pokusew\pcsclite\build\Release\pcsclite.node is not a valid Win32 application.
\\?\C:\inetpub\wwwroot\thaismartcardtrc\node_modules\@pokusew\pcsclite\build\Release\pcsclite.node
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1122:18)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at Module.Hook._require.Module.require (C:\Users\Administrator\AppData\Roaming\npm\node_modules\pm2\node_modules\require-in-the-middle\index.js:80:39)
    at require (internal/modules/cjs/helpers.js:88:18)
    at bindings (C:\inetpub\wwwroot\thaismartcardtrc\node_modules\bindings\bindings.js:112:48)
    at Object.<anonymous> (C:\inetpub\wwwroot\thaismartcardtrc\node_modules\@pokusew\pcsclite\lib\pcsclite.js:4:37)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
Error: \\?\C:\inetpub\wwwroot\thaismartcardtrc\node_modules\@pokusew\pcsclite\build\Release\pcsclite.node is not a valid Win32 application.
\\?\C:\inetpub\wwwroot\thaismartcardtrc\node_modules\@pokusew\pcsclite\build\Release\pcsclite.node
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1122:18)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at Module.Hook._require.Module.require (C:\Users\Administrator\AppData\Roaming\npm\node_modules\pm2\node_modules\require-in-the-middle\index.js:80:39)
    at require (internal/modules/cjs/helpers.js:88:18)
    at bindings (C:\inetpub\wwwroot\thaismartcardtrc\node_modules\bindings\bindings.js:112:48)
    at Object.<anonymous> (C:\inetpub\wwwroot\thaismartcardtrc\node_modules\@pokusew\pcsclite\lib\pcsclite.js:4:37)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
Error: \\?\C:\inetpub\wwwroot\thaismartcardtrc\node_modules\@pokusew\pcsclite\build\Release\pcsclite.node is not a valid Win32 application.
\\?\C:\inetpub\wwwroot\thaismartcardtrc\node_modules\@pokusew\pcsclite\build\Release\pcsclite.node
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1122:18)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at Module.Hook._require.Module.require (C:\Users\Administrator\AppData\Roaming\npm\node_modules\pm2\node_modules\require-in-the-middle\index.js:80:39)
    at require (internal/modules/cjs/helpers.js:88:18)
    at bindings (C:\inetpub\wwwroot\thaismartcardtrc\node_modules\bindings\bindings.js:112:48)
    at Object.<anonymous> (C:\inetpub\wwwroot\thaismartcardtrc\node_modules\@pokusew\pcsclite\lib\pcsclite.js:4:37)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
Error: \\?\C:\inetpub\wwwroot\thaismartcardtrc\node_modules\@pokusew\pcsclite\build\Release\pcsclite.node is not a valid Win32 application.
\\?\C:\inetpub\wwwroot\thaismartcardtrc\node_modules\@pokusew\pcsclite\build\Release\pcsclite.node
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1122:18)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at Module.Hook._require.Module.require (C:\Users\Administrator\AppData\Roaming\npm\node_modules\pm2\node_modules\require-in-the-middle\index.js:80:39)
    at require (internal/modules/cjs/helpers.js:88:18)
    at bindings (C:\inetpub\wwwroot\thaismartcardtrc\node_modules\bindings\bindings.js:112:48)
    at Object.<anonymous> (C:\inetpub\wwwroot\thaismartcardtrc\node_modules\@pokusew\pcsclite\lib\pcsclite.js:4:37)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
Error: \\?\C:\inetpub\wwwroot\thaismartcardtrc\node_modules\@pokusew\pcsclite\build\Release\pcsclite.node is not a valid Win32 application.
\\?\C:\inetpub\wwwroot\thaismartcardtrc\node_modules\@pokusew\pcsclite\build\Release\pcsclite.node
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1122:18)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at Module.Hook._require.Module.require (C:\Users\Administrator\AppData\Roaming\npm\node_modules\pm2\node_modules\require-in-the-middle\index.js:80:39)
    at require (internal/modules/cjs/helpers.js:88:18)
    at bindings (C:\inetpub\wwwroot\thaismartcardtrc\node_modules\bindings\bindings.js:112:48)
    at Object.<anonymous> (C:\inetpub\wwwroot\thaismartcardtrc\node_modules\@pokusew\pcsclite\lib\pcsclite.js:4:37)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
Error: \\?\C:\inetpub\wwwroot\thaismartcardtrc\node_modules\@pokusew\pcsclite\build\Release\pcsclite.node is not a valid Win32 application.
\\?\C:\inetpub\wwwroot\thaismartcardtrc\node_modules\@pokusew\pcsclite\build\Release\pcsclite.node
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1122:18)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at Module.Hook._require.Module.require (C:\Users\Administrator\AppData\Roaming\npm\node_modules\pm2\node_modules\require-in-the-middle\index.js:80:39)
    at require (internal/modules/cjs/helpers.js:88:18)
    at bindings (C:\inetpub\wwwroot\thaismartcardtrc\node_modules\bindings\bindings.js:112:48)
    at Object.<anonymous> (C:\inetpub\wwwroot\thaismartcardtrc\node_modules\@pokusew\pcsclite\lib\pcsclite.js:4:37)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
Error: \\?\C:\inetpub\wwwroot\thaismartcardtrc\node_modules\@pokusew\pcsclite\build\Release\pcsclite.node is not a valid Win32 application.
\\?\C:\inetpub\wwwroot\thaismartcardtrc\node_modules\@pokusew\pcsclite\build\Release\pcsclite.node
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1122:18)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at Module.Hook._require.Module.require (C:\Users\Administrator\AppData\Roaming\npm\node_modules\pm2\node_modules\require-in-the-middle\index.js:80:39)
    at require (internal/modules/cjs/helpers.js:88:18)
    at bindings (C:\inetpub\wwwroot\thaismartcardtrc\node_modules\bindings\bindings.js:112:48)
    at Object.<anonymous> (C:\inetpub\wwwroot\thaismartcardtrc\node_modules\@pokusew\pcsclite\lib\pcsclite.js:4:37)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
Error: \\?\C:\inetpub\wwwroot\thaismartcardtrc\node_modules\@pokusew\pcsclite\build\Release\pcsclite.node is not a valid Win32 application.
\\?\C:\inetpub\wwwroot\thaismartcardtrc\node_modules\@pokusew\pcsclite\build\Release\pcsclite.node
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1122:18)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at Module.Hook._require.Module.require (C:\Users\Administrator\AppData\Roaming\npm\node_modules\pm2\node_modules\require-in-the-middle\index.js:80:39)
    at require (internal/modules/cjs/helpers.js:88:18)
    at bindings (C:\inetpub\wwwroot\thaismartcardtrc\node_modules\bindings\bindings.js:112:48)
    at Object.<anonymous> (C:\inetpub\wwwroot\thaismartcardtrc\node_modules\@pokusew\pcsclite\lib\pcsclite.js:4:37)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
Error: \\?\C:\inetpub\wwwroot\thaismartcardtrc\node_modules\@pokusew\pcsclite\build\Release\pcsclite.node is not a valid Win32 application.
\\?\C:\inetpub\wwwroot\thaismartcardtrc\node_modules\@pokusew\pcsclite\build\Release\pcsclite.node
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1122:18)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at Module.Hook._require.Module.require (C:\Users\Administrator\AppData\Roaming\npm\node_modules\pm2\node_modules\require-in-the-middle\index.js:80:39)
    at require (internal/modules/cjs/helpers.js:88:18)
    at bindings (C:\inetpub\wwwroot\thaismartcardtrc\node_modules\bindings\bindings.js:112:48)
    at Object.<anonymous> (C:\inetpub\wwwroot\thaismartcardtrc\node_modules\@pokusew\pcsclite\lib\pcsclite.js:4:37)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
Error: \\?\C:\inetpub\wwwroot\thaismartcardtrc\node_modules\@pokusew\pcsclite\build\Release\pcsclite.node is not a valid Win32 application.
\\?\C:\inetpub\wwwroot\thaismartcardtrc\node_modules\@pokusew\pcsclite\build\Release\pcsclite.node
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1122:18)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at Module.Hook._require.Module.require (C:\Users\Administrator\AppData\Roaming\npm\node_modules\pm2\node_modules\require-in-the-middle\index.js:80:39)
    at require (internal/modules/cjs/helpers.js:88:18)
    at bindings (C:\inetpub\wwwroot\thaismartcardtrc\node_modules\bindings\bindings.js:112:48)
    at Object.<anonymous> (C:\inetpub\wwwroot\thaismartcardtrc\node_modules\@pokusew\pcsclite\lib\pcsclite.js:4:37)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
Error: \\?\C:\inetpub\wwwroot\thaismartcardtrc\node_modules\@pokusew\pcsclite\build\Release\pcsclite.node is not a valid Win32 application.
\\?\C:\inetpub\wwwroot\thaismartcardtrc\node_modules\@pokusew\pcsclite\build\Release\pcsclite.node
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1122:18)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at Module.Hook._require.Module.require (C:\Users\Administrator\AppData\Roaming\npm\node_modules\pm2\node_modules\require-in-the-middle\index.js:80:39)
    at require (internal/modules/cjs/helpers.js:88:18)
    at bindings (C:\inetpub\wwwroot\thaismartcardtrc\node_modules\bindings\bindings.js:112:48)
    at Object.<anonymous> (C:\inetpub\wwwroot\thaismartcardtrc\node_modules\@pokusew\pcsclite\lib\pcsclite.js:4:37)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
Error: \\?\C:\inetpub\wwwroot\thaismartcardtrc\node_modules\@pokusew\pcsclite\build\Release\pcsclite.node is not a valid Win32 application.
\\?\C:\inetpub\wwwroot\thaismartcardtrc\node_modules\@pokusew\pcsclite\build\Release\pcsclite.node
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1122:18)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at Module.Hook._require.Module.require (C:\Users\Administrator\AppData\Roaming\npm\node_modules\pm2\node_modules\require-in-the-middle\index.js:80:39)
    at require (internal/modules/cjs/helpers.js:88:18)
    at bindings (C:\inetpub\wwwroot\thaismartcardtrc\node_modules\bindings\bindings.js:112:48)
    at Object.<anonymous> (C:\inetpub\wwwroot\thaismartcardtrc\node_modules\@pokusew\pcsclite\lib\pcsclite.js:4:37)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
`

**Comment by somprasongd** [comment]
windows อะไรครับ 32/64 bit ครับ

node version อะไร ติดตั้งแบบ 32/64 bit ครับ

**Comment by menphurk** [comment]
> windows อะไรครับ 32/64 bit ครับ
> 
> node version อะไร ติดตั้งแบบ 32/64 bit ครับ

windows server 2016 64 bit
node version 14 ติดตั้ง 32 bit ครับ

**Comment by somprasongd** [comment]
อ่อ ติดตั้ง node 64 ครับ มันน่าจะไม่ตรงกันตอน build ออกมา

ไม่ทราบว่าเครื่องอ่านบัตรต่อไว้กับ windows server นี้หรอครับ เพราะว่าที่ผมทำไว้คือติดตั้งที่เครื่อง client ที่ต่อกับเครื่องอ่านบัตรครับ

**Comment by menphurk** [comment]
> อ่อ ติดตั้ง node 64 ครับ มันน่าจะไม่ตรงกันตอน build ออกมา
> 
> ไม่ทราบว่าเครื่องอ่านบัตรต่อไว้กับ windows server นี้หรอครับ เพราะว่าที่ผมทำไว้คือติดตั้งที่เครื่อง client ที่ต่อกับเครื่องอ่านบัตรครับ

อันนี้ ทำกับเครื่อง client ใช่หรือป่าวครับ ของผมที่ build กับเครื่อง server ครับ แต่ไม่ได้ต่อกับ เครื่องอ่านบัตรไว้ครับ เพราะอยู่คนละที่ครับ

**Comment by somprasongd** [comment]
โปรแกรมตัวนี้ ต้องติดตั้งที่เดัยวกับเครื่องอ่านบัตรครับ มันจะอ่านค่าออกมาจากบัตร ส่งออกไปครับ
